# Generated by Django 4.1.5 on 2023-01-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Description',
            field=models.TextField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='Requirment',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Courses/'),
        ),
        migrations.AddField(
            model_name='cours',
            name='suptitle',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
