# Generated by Django 4.1.5 on 2023-01-24 23:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Courses', '0002_cours_description_cours_requirment_cours_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
